# A docker compose file to startup all dependencies for running tests

services:
  redis:
    image: redis:8.2
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - redis_data:/data
    ports:
      - "16379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 20

  mongodb:
    image: mongo:8.0.14
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "37017:27017"
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping:1 }).ok' | grep 1" ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mongo_data:
  redis_data:
